//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by yoda_self_ordering.rc
//
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAIN_TOOLBAR                101
#define IDS_TOTAL_CUPS                  102
#define IDS_TOTAL_MONEY                 103
#define IDS_TIP_MAX_TOPPING             104
#define IDS_QRCODE_DESC                 105
#define IDS_SAVE_ORDER_ERROR            106
#define IDS_ERROR_CAPTION               107
#define IDR_MAINFRAME                   128
#define IDB_AIYU                        166
#define IDB_ALEO_VERA                   167
#define IDB_BLACK_PEARLS                169
#define IDB_COCONUT_JELLY               170
#define IDB_GRASS_JELLY                 171
#define IDB_GREEN_APPLE                 172
#define IDB_HOME                        173
#define IDB_ICE_CREAM                   174
#define IDB_MANGO_PUDDING               176
#define IDB_OREO                        180
#define IDB_RED_BEANS                   181
#define IDB_WHITE_PEARLS                182
#define IDB_PNG1                        185
#define IDR_PAGE_BACKGROUND             185
#define IDR_BCGP_VISUAL_XML1            188
#define IDR_BCGP_VISUAL_XML2            189
#define IDB_PNG2                        190
#define IDB_NO_TOPPING                  190
#define IDB_CONTINUE                    191
#define IDB_TALL_64                     195
#define IDB_TALL                        195
#define IDB_LARGE                       196
#define IDB_MEDIUM                      197
#define IDB_NORMAL_ICE                  201
#define IDB_FILTER_ICE                  202
#define IDB_LESS_ICE                    203
#define IDB_MORE_ICE                    204
#define IDB_ROOM_TEMP                   205
#define IDB_WARM_WATER                  206
#define IDB_BACK                        207
#define IDB_NEXT                        208
#define IDR_BCGP_VISUAL_XML3            210
#define IDR_BCGP_VISUAL_XML4            211
#define IDB_PNG3                        212
#define IDR_BCGP_VISUAL_XML5            213
#define IDR_BCGP_VISUAL_XML6            214
#define IDB_BITMAP2                     217
#define IDB_SPLASH                      217
#define IDB_PNG4                        218
#define IDB_CART                        218
#define IDD_DIALOG1                     220
#define IDD_CASH_POP                    220
#define IDB_PNG5                        222
#define IDB_COUNTER                     225
#define IDB_NETS                        226
#define IDR_BCGP_VISUAL_XML7            227
#define IDB_IPAY                        228
#define IDR_BCGP_VISUAL_XML8            231
#define IDB_HOME_ORDER                  232
#define IDB_PNG7                        233
#define IDB_HOME_CARD                   233
#define IDB_CHINESE                     234
#define IDB_PNG8                        235
#define IDB_ENGLISH                     235
#define IDD_DIALOG2                     237
#define IDD_DIALOG_NOTICE               237
#define IDD_DIALOG3                     239
#define IDD_SHOW_QRCODE                 239
#define IDB_NETS_FLASHPAY               241
#define IDB_PNG9                        245
#define IDB_NETS_QR                     245
#define IDD_DIALOG4                     247
#define IDD_DIALOG5                     249
#define IDD_DIALOG_GIF                  249
#define IDR_GIF1                        253
#define IDD_PAYMENT_STATUS              254
#define IDB_PNG6                        256
#define IDB_PAY_FAILED                  256
#define IDD_NETS_OPER                   257
#define IDB_NETSLOG                     259
#define IDB_PAY_SUCCESS                 260
#define IDB_PAY                         261
#define IDB_PNG10                       262
#define IDR_GIF2                        263
#define IDR_GIF_NETSDEBIT               263
#define IDR_GIF_NETSFLASHPAY            264
#define IDR_GIF4                        265
#define IDR_GIF_NETSQRCODE              265
#define IDB_CAPTION_PAY_BUTTON          266
#define IDB_PNG11                       267
#define IDB_VOUCHER                     268
#define IDD_DIALOG_VOUCHER              269
#define IDB_NETS_FLASHPAY_DISABLE       271
#define IDB_NETS_QR_DISABLE             272
#define IDB_PNG14                       273
#define IDB_NETS_DISABLE                273
#define IDD_DIALOG_VOUCHERS             274
#define IDB_PNG12                       276
#define IDB_VOUCHERICON                 276
#define IDB_COUNTER_DISABLE             277
#define IDB_IPAY_DISABLE                278
#define IDB_FREE                        279
#define IDB_PNG15                       280
#define IDB_FREE_DISABLE                280
#define IDC_BUTTON_HOME                 1054
#define IDC_STATIC_TIP1                 1055
#define IDC_STATIC_TIP2                 1056
#define IDC_STATIC_TIP3                 1057
#define IDC_EDIT1                       1058
#define IDC_EDIT2                       1059
#define IDC_STATIC_DESC                 1059
#define IDC_EDIT3                       1060
#define IDC_QR_PIC                      1060
#define IDC_EXIT_DESC                   1061
#define IDC_STATIC_GIF                  1069
#define IDC_BUTTON_TRY                  1071
#define IDC_STATIC_ICON                 1072
#define IDC_BUTTON_LOGON                1073
#define IDC_BUTTON_SETTLEMENT           1074
#define IDC_STATIC_LOG                  1075
#define IDC_PROGRESS1                   1076
#define IDC_PROGRESS                    1076
#define IDC_STATIC_LOGO                 1077
#define IDC_LIST_VOUCHER                1080
#define IDC_BUTTON1                     1081
#define IDC_BUTTON_OK                   1081
#define IDC_CLOSE                       1081
#define IDC_STATIC_TIP                  1083
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_TOOLBARS                32771
#define ID_BACK                         32775
#define ID_HOME                         32776
#define ID_NEXT                         32777
#define ID_PAYMENT                      32778
#define ID_CART                         32779
#define ID_VIEW_USER_TOOLBAR1           32793
#define ID_VIEW_USER_TOOLBAR2           32794
#define ID_VIEW_USER_TOOLBAR3           32795
#define ID_VIEW_USER_TOOLBAR4           32796
#define ID_VIEW_USER_TOOLBAR5           32797
#define ID_VIEW_USER_TOOLBAR6           32798
#define ID_VIEW_USER_TOOLBAR7           32799
#define ID_VIEW_USER_TOOLBAR8           32800
#define ID_VIEW_USER_TOOLBAR9           32801
#define ID_VIEW_USER_TOOLBAR10          32802

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        281
#define _APS_NEXT_COMMAND_VALUE         32869
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           117
#endif
#endif
